function [varargout]=Ben(varargin)
action = varargin{1};
global Data
global Ben
global Log
switch action
case 'Initial'
   
Ben.Figure = figure('Color',[0.8 0.8 0.8], ...
	'FileName','F:\HVRClab\Zeng\ben.m', ...
	'PaperPosition',[18 180 576 432], ...
	'PaperUnits','points', ...
	'Position',[420 251 560 420], ...
	'Tag','Fig1', ...
	'ToolBar','none');
Ben.Axis = axes('Parent',Ben.Figure, ...
	'Units','pixels', ...
	'CameraUpVector',[0 1 0], ...
	'Color',[1 1 1], ...
	'Position',[35 23 500 97], ...
	'Tag','Axes1', ...
	'XColor',[0 0 0], ...
	'YColor',[0 0 0], ...
	'ZColor',[0 0 0]);
h2 = text('Parent',Ben.Axis, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',[0.498046875 -0.25 9.160254037844386], ...
	'Tag','Axes1Text4', ...
	'VerticalAlignment','cap');
set(get(h2,'Parent'),'XLabel',h2);
h2 = text('Parent',Ben.Axis, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',[-0.0546875 0.4895833333333335 9.160254037844386], ...
	'Rotation',90, ...
	'Tag','Axes1Text3', ...
	'VerticalAlignment','baseline');
set(get(h2,'Parent'),'YLabel',h2);
h2 = text('Parent',Ben.Axis, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','right', ...
	'Position',[-0.052734375 4.125 9.160254037844386], ...
	'Tag','Axes1Text2');
set(get(h2,'Parent'),'ZLabel',h2);
h2 = text('Parent',Ben.Axis, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',[0.498046875 1.072916666666667 9.160254037844386], ...
	'Tag','Axes1Text1', ...
	'VerticalAlignment','bottom');
set(get(h2,'Parent'),'Title',h2);
%Ben.Blockout = uicontrol('Parent',Ben.Figure, ...
%	'Units','points', ...
%	'BackgroundColor',[1 1 1], ...
%	'ListboxTop',0, ...
%	'Position',[19.5 152.25 65.25 14.25], ...
%  'Style','edit', ...
% 'String','300',...
%	'Tag','EditText1');
Ben.Pacing = uicontrol('Parent',Ben.Figure, ...
	'Units','points', ...
   'BackgroundColor',[1 1 1], ...
   'callback','Ben Pacing',...
	'ListboxTop',0, ...
	'Position',[20.25 210 30.75 16.5], ...
   'Style','edit', ...
   'String','258',...
	'Tag','EditText2');
Ben.Text = uicontrol('Parent',Ben.Figure, ...
	'Units','points', ...
	'BackgroundColor',[0.752941176470588 0.752941176470588 0.752941176470588], ...
	'ListboxTop',0, ...
	'Position',[19.5 98.25 45 15], ...
	'String','Signal', ...
	'Style','text', ...
	'Tag','StaticText1');
%Ben.Text = uicontrol('Parent',Ben.Figure, ...
%	'Units','points', ...
%	'ListboxTop',0, ...
%	'Position',[19.5 169.5 45 15], ...
%	'String','Blockout', ...
%	'Style','text', ...
%	'Tag','StaticText2');
Ben.Text = uicontrol('Parent',Ben.Figure, ...
	'Units','points', ...
   'BackgroundColor',[0.752941176470588 0.752941176470588 0.752941176470588], ...
   'callback','Ben AlignFrames',...
	'ListboxTop',0, ...
	'Position',[308.25 234 65.25 25.5], ...
	'String','Average Signal', ...
	'Tag','Pushbutton1');
Ben.Text = uicontrol('Parent',Ben.Figure, ...
	'Units','points', ...
	'BackgroundColor',[0.752941176470588 0.752941176470588 0.752941176470588], ...
	'ListboxTop',0, ...
	'Position',[19.5 231 69 15], ...
	'String','Pacing Channel', ...
	'Style','text', ...
	'Tag','StaticText3');
if nargout > 0, fig = Ben.Figure; end
Ben.ChLabel=varargin{4};
Ben.Z=varargin{2};
Ben.X1X2=varargin{3};
Ben.Annote=varargin{5};
Ben.Data=Data{2}(:,Ben.X1X2(1):Ben.X1X2(2));
Ben.Channel=str2num(get(Ben.Pacing,'String'))+1;
Ben.DataCh=Ben.Data(Ben.Channel,:);
plot(Ben.DataCh,'Parent',Ben.Axis);
axis tight


case 'Pacing'
      Ben.Channel=str2num(get(Ben.Pacing,'String'))+1;
      Ben.DataCh=Ben.Data(Ben.Channel,:);
      plot(Ben.DataCh,'Parent',Ben.Axis);
      axis tight
      
   case 'AlignFrames'
      Ben.Sights=[];
      Sights=[];
      a=max(Ben.DataCh);
      b=min(Ben.DataCh);
      c=.1*(a-b)+b;
      %plot(Ben.DataCh,'Parent',Ben.Axis);
      %line([0 5000],[c c])
      %pause
 Sights=find(Ben.DataCh<.1*(a-b)+b);
 index=1;
 first=1;
   for count=1:length(Sights)-1;
      Difference=Sights(count+1)-Sights(count);
      if Difference==1 & first==1;
         Ben.Sights(index)=Sights(count);
         index=index+1;
         first=0;
      elseif Difference>1
         first=1;
      elseif Difference>1 & first==1;
         Ben.Sights=Sights;
      end
   end
%   Ben.Sights
   old=Ben.Data(:,Ben.Sights(1):Ben.Sights(2)-1);
   Ben.NewData=old;
   gap=abs(Ben.Sights(1)-Ben.Sights(2)+1);
   for count=2:length(Ben.Sights);
      %     if count~=length(Ben.Sights);
      if (Ben.Sights(count)+gap)<length(Ben.Data);
         new=Ben.Data(:,Ben.Sights(count):Ben.Sights(count)+gap);
         [x y]=size(Ben.NewData);
      else
         %disp('End of Data Set')
         [x y]=size(Ben.NewData);
         new=0*ones(x,y);
         zzz=length(Ben.NewData)-Ben.Sights(count)+1;
         new(:,1:zzz)=Ben.Data(:,Ben.Sights(count):length(Ben.NewData));
      end
     Ben.NewData=old+new;
      old=Ben.NewData;
   end
   plot(Ben.NewData(1,:)-1,'Parent',Ben.Axis);
   axis tight
 
[Ben.Filename, Ben.Pathname] = uiputfile('c:\windows\desktop\*.*', 'Save File');
fid1=fopen(strcat(Log.Head.Path,Log.Head.FileName,'.h'));
junk=fread(fid1);


temp1=junk';
for count=1:length(junk)
   temp2=setstr(temp1(count));
     if temp2=='l'
        if setstr(temp1(count+1))=='e'
           if setstr(temp1(count+2))=='s'
              for index=4:9
                 if setstr(temp1(count+index))=='c'
                    stop=index-1;
                 else
                    temp3(index-3)=setstr(temp1(count+index));
                    stop=index-1;
                 end
              end
              pointer=count;
           end
        end
     end
  end
fclose(fid1);
filenameh=[Ben.Pathname Ben.Filename '.h'];
fids=fopen(strcat(Log.Head.Path,Log.Head.FileName),'r');
header=fread(fids,31,'int8');
%header1=['COLUMN BINARY FILE'];
%header2=['2t260c0c0e'];
fclose(fids);

fid2=fopen(filenameh,'w');
fwrite(fid2,junk(1:pointer+3));
fwrite(fid2,num2str(y),'char');
fwrite(fid2,junk(pointer+stop:length(junk)));
fclose(fid2);
fid3=fopen([Ben.Pathname Ben.Filename],'w','b');
fwrite(fid3,header,'int8');
%fwrite(fid3,header1,'int8');
%fwrite(fid3,header2,'int8');
%fclose(fid3);
%fid3=fopen([Ben.Pathname Ben.Filename],'a+');
%header=fread(fids,32,'uchar');

% 259 and 0 seemed to be switched. This part unswitches it.
Ben.NewData1=[];
Ben.NewData1(1:x-1,:)=Ben.NewData(2:x,:);
Ben.NewData1(x,:)=Ben.NewData(1,:);


for count=1:y
%for count=1:x
   fwrite(fid3,Ben.NewData1(:,count),'int16');
  % fwrite(fid3,Ben.NewData1(count,:),'int16');
end

fclose(fid3);
%errordlg('Done')
%msgbox('Done')


end
