function Mov_Filters(varargin)
global UD
global Movielog
global Log
global Data
global Movs
global axishd
global Stripchart
global LUTDisplay
global Filters

action = varargin{1};
switch action
%---------------------------------------------------   

case 'Initial'

Filters.Order=1;
Filters.LowCuttoff=60;
Filters.HighCuttoff=120;
Filters.PassRipple=1;
Filters.StopRipple=1;
Filters.name='b ';
Filters.Type='low ';
Filters.Apply=0;
UD.Ref.FontSize=8;
Filters.old=Movs.newarray;
   Filters.Figure=figure;
   FG_Size=[500 90 505 100];   
   set(Filters.Figure,...
         'Color',[0.8 0.8 0.8], ...
       	 'DeleteFcn','',...
         'menu','none',...
         'Name','Digital Filters',...
         'NumberTitle','off',...
         'Position',FG_Size, ...
         'Tag','Movielog');
  values = {['Butterworth';'Chebychev 1';'Chebychev 2';'Elliptical ';]};
  Filters.Filters = uicontrol('Parent',Filters.Figure, ...
        'Units','points', ...
        'BackgroundColor',[0.733333 0.733333 0.733333], ...
   	    'callback','Mov_Filters FilterName',...
        'Enable','on', ...
        'ListboxTop',0, ...
        'Position',[5 32 70 15], ...
        'String',values, ...
        'Style','popupmenu', ...
        'Tag','PopupMenu1', ...
        'Value',1); 
  values = {['Low Pass ';'High Pass';'Band Pass';'Band Stop';]};
  Filters.Types = uicontrol('Parent',Filters.Figure, ...
        'Units','points', ...
        'BackgroundColor',[0.733333 0.733333 0.733333], ...
   	    'callback','Mov_Filters FilterType',...
        'Enable','on', ...
        'ListboxTop',0, ...
        'Position',[80 32 70 15], ...
        'String',values, ...
        'Style','popupmenu', ...
        'Tag','PopupMenu1', ...
        'Value',1); 	
%@@@@@@@@@@@@@@@@@@@@@@@@@@@
%     TEXT
%@@@@@@@@@@@@@@@@@@@@@@@@@@@@
 Filters.text1 =uicontrol('Parent',Filters.Figure, ...
            'Units','pixels',...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'FontName','Times',...
            'FontUnits','points',...
            'FontSize',9,...
            'FontWeight','bold',...
            'FontAngle','normal',...
            'HorizontalAlignment','left', ...
            'Position',[5 75 120 15], ...
            'String','Filter Name ', ...
            'Style','text', ...
            'Tag','StaticText2',...
            'visible','on');

 Filters.Text.Order =uicontrol('Parent',Filters.Figure, ...
            'Units','pixels',...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'FontName','Times',...
            'FontUnits','points',...
            'FontSize',UD.Ref.FontSize,...
            'FontWeight','bold',...
            'FontAngle','normal',...
            'HorizontalAlignment','left', ...
            'Position',[218 75 50 15], ...
            'String','Order ', ...
            'Style','text', ...
            'Tag','StaticText2',...
            'visible','on');			
 Filters.Text.Cuttoff.Low =uicontrol('Parent',Filters.Figure, ...
            'Units','pixels',...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'FontName','Times',...
            'FontUnits','points',...
            'FontSize',UD.Ref.FontSize,...
            'FontWeight','bold',...
            'FontAngle','normal',...
            'HorizontalAlignment','left', ...
            'Position',[278 75 50 25], ...
            'String','Low Cut-Off ', ...
            'Style','text', ...
            'Tag','StaticText2',...
            'visible','on');
 Filters.Text.Cuttoff.High =uicontrol('Parent',Filters.Figure, ...
            'Units','pixels',...
            'BackgroundColor',[0.8 0.8 0.8], ...
			'Enable','off',...
            'FontName','Times',...
            'FontUnits','points',...
            'FontSize',UD.Ref.FontSize,...
            'FontWeight','bold',...
            'FontAngle','normal',...
            'HorizontalAlignment','left', ...
            'Position',[338 75 50 25], ...
            'String','High Cut-Off ', ...
            'Style','text', ...
            'Tag','StaticText2',...
            'visible','on');	
 Filters.Text.Type =uicontrol('Parent',Filters.Figure, ...
            'Units','pixels',...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'FontName','Times',...
            'FontUnits','points',...
            'FontSize',9,...
            'FontWeight','bold',...
            'FontAngle','normal',...
            'HorizontalAlignment','left', ...
            'Position',[118 75 100 15], ...
            'String','Filter Type ', ...
            'Style','text', ...
            'Tag','StaticText2',...
            'visible','on');
 Filters.Text.PRipple =uicontrol('Parent',Filters.Figure, ...
            'Units','pixels',...
            'BackgroundColor',[0.8 0.8 0.8], ...
			'Enable','off',...
            'FontName','Times',...
            'FontUnits','points',...
            'FontSize',UD.Ref.FontSize,...
            'FontWeight','bold',...
            'FontAngle','normal',...
            'HorizontalAlignment','left', ...
            'Position',[398 75 50 25], ...
            'String','Pass Ripple ', ...
            'Style','text', ...
            'Tag','StaticText2',...
            'visible','on');
 Filters.Text.SRipple =uicontrol('Parent',Filters.Figure, ...
            'Units','pixels',...
            'BackgroundColor',[0.8 0.8 0.8], ...
			'Enable','off',...
            'FontName','Times',...
            'FontUnits','points',...
            'FontSize',UD.Ref.FontSize,...
            'FontWeight','bold',...
            'FontAngle','normal',...
            'HorizontalAlignment','left', ...
            'Position',[458 75 50 25], ...
            'String','Stop Ripple ', ...
            'Style','text', ...
            'Tag','StaticText2',...
            'visible','on');
			
Filters.Text.One =uicontrol('Parent',Filters.Figure, ...
            'Units','pixels',...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'FontName','Times',...
            'FontUnits','points',...
            'FontSize',UD.Ref.FontSize-1,...
            'FontWeight','bold',...
            'FontAngle','normal',...
            'HorizontalAlignment','left', ...
            'Position',[308 43 50 25], ...
            'String','Hz', ...
            'Style','text', ...
            'Tag','StaticText2',...
            'visible','on');
Filters.Text.One =uicontrol('Parent',Filters.Figure, ...
            'Units','pixels',...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'FontName','Times',...
            'FontUnits','points',...
            'FontSize',UD.Ref.FontSize-1,...
            'FontWeight','bold',...
            'FontAngle','normal',...
            'HorizontalAlignment','left', ...
            'Position',[368 43 50 25], ...
            'String','Hz', ...
            'Style','text', ...
            'Tag','StaticText2',...
            'visible','on');
Filters.Text.One =uicontrol('Parent',Filters.Figure, ...
            'Units','pixels',...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'FontName','Times',...
            'FontUnits','points',...
            'FontSize',UD.Ref.FontSize-1,...
            'FontWeight','bold',...
            'FontAngle','normal',...
            'HorizontalAlignment','left', ...
            'Position',[428 43 50 25], ...
            'String','dB', ...
            'Style','text', ...
            'Tag','StaticText2',...
            'visible','on');
Filters.Text.One =uicontrol('Parent',Filters.Figure, ...
            'Units','pixels',...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'FontName','Times',...
            'FontUnits','points',...
            'FontSize',UD.Ref.FontSize-1,...
            'FontWeight','bold',...
            'FontAngle','normal',...
            'HorizontalAlignment','left', ...
            'Position',[488 43 15 25], ...
            'String','dB', ...
            'Style','text', ...
            'Tag','StaticText2',...
            'visible','on');
 %######################
 % ALL EDIT BOXES
 %######################
 Filters.Box.Order = uicontrol('Parent',Filters.Figure, ...
        'Units','pixels',...
		'callback','Mov_Filters(''IntCheck'')',...
   	    'BackgroundColor',[1 1 1], ...
        'FontName','Times',...
        'FontUnits','points',...
        'FontSize',UD.Ref.FontSize,...
        'FontWeight','normal',...
        'FontAngle','normal',...
        'HorizontalAlignment','right',...
        'Position',[218 50 30 22], ...
        'String',Filters.Order, ...
   	    'Style','edit', ...
	    'Tag','EditOrder');
	
 Filters.Box.Cuttoff.Low = uicontrol('Parent',Filters.Figure, ...
        'Units','pixels',...
   	    'BackgroundColor',[1 1 1], ...
        'FontName','Times',...
        'FontUnits','points',...
        'FontSize',UD.Ref.FontSize,...
        'FontWeight','normal',...
        'FontAngle','normal',...
        'HorizontalAlignment','right',...
        'Position',[278 50 30 22], ...
        'String',Filters.LowCuttoff, ...
   	    'Style','edit', ...
	    'Tag','EditOrder');
 Filters.Box.Cuttoff.High = uicontrol('Parent',Filters.Figure, ...
        'Units','pixels',...
   	    'BackgroundColor',[1 1 1], ...
		'Enable','off',...
        'FontName','Times',...
        'FontUnits','points',...
        'FontSize',UD.Ref.FontSize,...
        'FontWeight','normal',...
        'FontAngle','normal',...
        'HorizontalAlignment','right',...
        'Position',[338 50 30 22], ...
        'String',Filters.HighCuttoff, ...
   	    'Style','edit', ...
	    'Tag','EditOrder');	
Filters.Box.PRipple = uicontrol('Parent',Filters.Figure, ...
        'Units','pixels',...
   	    'BackgroundColor',[1 1 1], ...
		'Enable','off',...
        'FontName','Times',...
        'FontUnits','points',...
        'FontSize',UD.Ref.FontSize,...
        'FontWeight','normal',...
        'FontAngle','normal',...
        'HorizontalAlignment','right',...
        'Position',[398 50 30 22], ...
        'String',Filters.PassRipple, ...
   	    'Style','edit', ...
	    'Tag','EditOrder');	
Filters.Box.SRipple = uicontrol('Parent',Filters.Figure, ...
        'Units','pixels',...
   	    'BackgroundColor',[1 1 1], ...
		'Enable','off',...
        'FontName','Times',...
        'FontUnits','points',...
        'FontSize',UD.Ref.FontSize,...
        'FontWeight','normal',...
        'FontAngle','normal',...
        'HorizontalAlignment','right',...
        'Position',[458 50 30 22], ...
        'String',Filters.StopRipple, ...
   	    'Style','edit', ...
	    'Tag','EditOrder');	
		
		%--------------------
		% APPLY BUTTON
		%--------------------
   Filter.Button.Apply = uicontrol('Parent',Filters.Figure, ...
         'Units','pixels',...
         'FontName','Times',...
         'FontUnits','points',...
         'FontSize',UD.Ref.FontSize,...
         'FontWeight','normal',...
         'FontAngle','normal',...
         'Position',[250 15 60 22], ...
         'String','APPLY', ...
         'callback','Mov_Filters(''Apply'')',...  
         'Tag','Pushbutton1');
   Filter.Button.Preview = uicontrol('Parent',Filters.Figure, ...
         'Units','pixels',...
         'FontName','Times',...
         'FontUnits','points',...
         'FontSize',UD.Ref.FontSize,...
         'FontWeight','normal',...
         'FontAngle','normal',...
         'Position',[150 15 60 22], ...
         'String','Preview', ...
         'callback','Mov_Filters(''Preview'')',...  
         'Tag','Pushbutton1');
	Filter.Button.Cancel = uicontrol('Parent',Filters.Figure, ...
         'Units','pixels',...
         'FontName','Times',...
         'FontUnits','points',...
         'FontSize',UD.Ref.FontSize,...
         'FontWeight','normal',...
         'FontAngle','normal',...
         'Position',[350 15 60 22], ...
         'String','Cancel', ...
         'callback','Mov_Filters(''Cancel'')',...  
         'Tag','Pushbutton1');
   %=====================================================================================			
   %=====================================================================================
   %=====================================================================================
   
case 'FilterName'
   Filtname=get(Filters.Filters,'Value');
   switch Filtname 
   case 1,       
		Filters.name=['b '];
	    set(Filters.Box.SRipple,'Enable','off');
		set(Filters.Text.SRipple,'Enable','off');
   case 2,
		Filters.name=['c1'];
		set(Filters.Box.PRipple,'Enable','on');
		set(Filters.Text.PRipple,'Enable','on');
		set(Filters.Box.SRipple,'Enable','off');
		set(Filters.Text.SRipple,'Enable','off');
   case 3,       
		Filters.name=['c2']; 
		set(Filters.Box.PRipple,'Enable','on');
		set(Filters.Text.PRipple,'Enable','on');
		set(Filters.Box.SRipple,'Enable','off');
		set(Filters.Text.SRipple,'Enable','off');
   case 4,
		Filters.name=['e '];
		set(Filters.Box.PRipple,'Enable','on');
		set(Filters.Text.PRipple,'Enable','on');
		set(Filters.Box.SRipple,'Enable','on');
		set(Filters.Text.SRipple,'Enable','on');
	end   


case 'FilterType'
	FiltType=get(Filters.Types,'Value');
	switch FiltType
	case 1,
		Filters.Type='low ';
	    set(Filters.Box.Cuttoff.High,'Enable','off');
		set(Filters.Text.Cuttoff.High,'Enable','off');
		set(Filters.Box.Cuttoff.Low,'Enable','on');
		set(Filters.Text.Cuttoff.Low,'Enable','on');
	case 2,
		Filters.Type='high';
	    set(Filters.Box.Cuttoff.High,'Enable','on');
		set(Filters.Text.Cuttoff.High,'Enable','on');
		set(Filters.Box.Cuttoff.Low,'Enable','off');
		set(Filters.Text.Cuttoff.Low,'Enable','off');	
	case 3
		Filters.Type='pass';
		set(Filters.Box.Cuttoff.High,'Enable','on');
		set(Filters.Text.Cuttoff.High,'Enable','on');
		set(Filters.Box.Cuttoff.Low,'Enable','on');
		set(Filters.Text.Cuttoff.Low,'Enable','on');
	case 4
		Filters.Type='stop';
		set(Filters.Box.Cuttoff.High,'Enable','on');
		set(Filters.Text.Cuttoff.High,'Enable','on');
		set(Filters.Box.Cuttoff.Low,'Enable','on');
		set(Filters.Text.Cuttoff.Low,'Enable','on');
	end
	

case 'Preview'
	Filters.Order=str2num(get(Filters.Box.Order,'String'));
	Filters.LowCuttoff=str2num(get(Filters.Box.Cuttoff.Low,'String'))/Log.Head.SRate;
	Filters.HighCuttoff=str2num(get(Filters.Box.Cuttoff.High,'String'))/Log.Head.SRate;
	Filters.PassRipple=str2num(get(Filters.Box.PRipple,'String'));
	Filters.StopRipple=str2num(get(Filters.Box.SRipple,'String'));
switch Filters.name
	case 'b '
		if Filters.Type=='low '
			[B,A]=butter(Filters.Order,Filters.LowCuttoff);
		elseif Filters.Type=='high'
			[B,A]=butter(Filters.Order,Filters.HighCuttoff,Filters.Type);
		elseif Filters.Type=='pass'
			[B,A]=butter(Filters.Order,[Filters.LowCuttoff,Filters.HighCuttoff]);
		elseif Filters.Type=='stop'
			[B,A]=butter(Filters.Order,[Filters.LowCuttoff,Filters.HighCuttoff],Filters.Type);
		end
	
	case 'c1'
		if Filters.Type=='low '
			[B,A]=cheby1(Filters.Order,Filters.PassRipple,Filters.LowCuttoff);
		elseif Filters.Type=='high'
			[B,A]=cheby1(Filters.Order,Filters.PassRipple,Filters.HighCuttoff,Filters.Type);
		elseif Filters.Type=='pass'
			[B,A]=cheby1(Filters.Order,Filters.PassRipple,[Filters.LowCuttoff,Filters.HighCuttoff]);
		elseif Filters.Type=='stop'
			[B,A]=cheby1(Filters.Order,Filters.PassRipple,[Filters.LowCuttoff,Filters.HighCuttoff],Filters.Type);
		end
	
	case 'c2'
		if Filters.Type=='low '
			[B,A]=cheby2(Filters.Order,Filters.PassRipple,Filters.LowCuttoff);
		elseif Filters.Type=='high'
			[B,A]=cheby2(Filters.Order,Filters.PassRipple,Filters.HighCuttoff,Filters.Type);
		elseif Filters.Type=='pass'
			[B,A]=cheby2(Filters.Order,Filters.PassRipple,[Filters.LowCuttoff,Filters.HighCuttoff]);
		elseif Filters.Type=='stop'
			[B,A]=cheby2(Filters.Order,Filters.PassRipple,[Filters.LowCuttoff,Filters.HighCuttoff],Filters.Type);
		end
	
	case 'e '
		if Filters.Type=='low '
			[B,A]=ellip(Filters.Order,Filters.PassRipple,Filters.StopRipple,'low');
		elseif Filters.Type=='high'
			[B,A]=ellip(Filters.Order,Filters.PassRipple,Filters.StopRipple,Filters.HighCuttoff,Filters.Type);
		elseif Filters.Type=='pass'
			[B,A]=ellip(Filters.Order,Filters.PassRipple,Filters.StopRipple,[Filters.LowCuttoff,Filters.HighCuttoff]);
		elseif Filters.Type=='stop'
			[B,A]=ellip(Filters.Order,Filters.PassRipple,Filters.StopRipple,[Filters.LowCuttoff,Filters.HighCuttoff],Filters.Type);
		end		
	end
Sign=Filters.old;

if get(Movs.Button.Global,'value')==1
	Movs.newarray=filter(B,A,Sign);
elseif get(Movs.Button.Local,'value')==1
	Movs.newarray(:,Movs.Current_ch)=filter(B,A,Sign(:,Movs.Current_ch));
end
Filters.Apply=1;
    if Movs.Signal.True==1;
       Mov_Movie 'Signal'
    end
figure(Filters.Figure)	



case 'Apply'
   Temparray=Movs.newarray;
%   save Temparray Temparray;
   clear Temparray;
	Filters.Order=str2num(get(Filters.Box.Order,'String'));
	Filters.LowCuttoff=str2num(get(Filters.Box.Cuttoff.Low,'String'))/Log.Head.SRate;
	Filters.HighCuttoff=str2num(get(Filters.Box.Cuttoff.High,'String'))/Log.Head.SRate;
	Filters.PassRipple=str2num(get(Filters.Box.PRipple,'String'));
	Filters.StopRipple=str2num(get(Filters.Box.SRipple,'String'));
switch Filters.name
	case 'b '
		if Filters.Type=='low '
			[B,A]=butter(Filters.Order,Filters.LowCuttoff);
		elseif Filters.Type=='high'
			[B,A]=butter(Filters.Order,Filters.HighCuttoff,Filters.Type);
		elseif Filters.Type=='pass'
			[B,A]=butter(Filters.Order,[Filters.LowCuttoff,Filters.HighCuttoff]);
		elseif Filters.Type=='stop'
			[B,A]=butter(Filters.Order,[Filters.LowCuttoff,Filters.HighCuttoff],Filters.Type);
		end
	
	case 'c1'
		if Filters.Type=='low '
			[B,A]=cheby1(Filters.Order,Filters.PassRipple,Filters.LowCuttoff);
		elseif Filters.Type=='high'
			[B,A]=cheby1(Filters.Order,Filters.PassRipple,Filters.HighCuttoff,Filters.Type);
		elseif Filters.Type=='pass'
			[B,A]=cheby1(Filters.Order,Filters.PassRipple,[Filters.LowCuttoff,Filters.HighCuttoff]);
		elseif Filters.Type=='stop'
			[B,A]=cheby1(Filters.Order,Filters.PassRipple,[Filters.LowCuttoff,Filters.HighCuttoff],Filters.Type);
		end
	
	case 'c2'
		if Filters.Type=='low '
			[B,A]=cheby2(Filters.Order,Filters.PassRipple,Filters.LowCuttoff);
		elseif Filters.Type=='high'
			[B,A]=cheby2(Filters.Order,Filters.PassRipple,Filters.HighCuttoff,Filters.Type);
		elseif Filters.Type=='pass'
			[B,A]=cheby2(Filters.Order,Filters.PassRipple,[Filters.LowCuttoff,Filters.HighCuttoff]);
		elseif Filters.Type=='stop'
			[B,A]=cheby2(Filters.Order,Filters.PassRipple,[Filters.LowCuttoff,Filters.HighCuttoff],Filters.Type);
		end
	
	case 'e '
		if Filters.Type=='low '
			[B,A]=ellip(Filters.Order,Filters.PassRipple,Filters.StopRipple,'low');
		elseif Filters.Type=='high'
			[B,A]=ellip(Filters.Order,Filters.PassRipple,Filters.StopRipple,Filters.HighCuttoff,Filters.Type);
		elseif Filters.Type=='pass'
			[B,A]=ellip(Filters.Order,Filters.PassRipple,Filters.StopRipple,[Filters.LowCuttoff,Filters.HighCuttoff]);
		elseif Filters.Type=='stop'
			[B,A]=ellip(Filters.Order,Filters.PassRipple,Filters.StopRipple,[Filters.LowCuttoff,Filters.HighCuttoff],Filters.Type);
		end		
	end

Filters.LowCuttoff=Filters.LowCuttoff*Log.Head.SRate;
Filters.HighCuttoff=Filters.HighCuttoff*Log.Head.SRate;
Sign=Filters.old;



if get(Movs.Button.Global,'value')==1
	Movs.newarray=filter(B,A,Sign);
	Mov_Movielog('Add',['Filt ',Filters.name,' ',num2str(Filters.Type),' ',num2str(Filters.Order),' ',num2str(Filters.LowCuttoff),' ',num2str(Filters.HighCuttoff),' ',num2str(Filters.PassRipple),' ',num2str(Filters.StopRipple)]) ;
elseif get(Movs.Button.Local,'value')==1
	Movs.newarray(:,Movs.Current_ch)=filter(B,A,Sign(:,Movs.Current_ch));
	Mov_Movielog('Add Local',['Filt ',Filters.name,' ',num2str(Filters.Type),' ',num2str(Filters.Order),' ',num2str(Filters.LowCuttoff),' ',num2str(Filters.HighCuttoff),' ',num2str(Filters.PassRipple),' ',num2str(Filters.StopRipple),' ',num2str(Movs.Badpic)]);
end
%set(Movs.Button.FS,'value',0)
    if Movs.Signal.True==1;
       Mov_Movie 'Signal'
    end
    close(Filters.Figure)
    Mov_Movie('Fullscale')


case 'Cancel'
	Movs.newarray=Filters.old;
    if Movs.Signal.True==1;
       Mov_Movie 'Signal'
    end
close(Filters.Figure)

case 'IntCheck'

	  order=str2num(get(Filters.Box.Order,'String'));
   if ceil(order)~=fix(order)
	      set(Filters.Box.Order,'String',order);
         Mov('Error','Integer Numbers Only');
      elseif order>-1
         set(Filters.Box.Order,'String',order);
         Filters.Order=order;
      else;
         set(Filters.Box.Order,'String',order);
         Mov('Error','The number is out of range');
      end
  
  
case 'Loaded'
   Temparray=Movs.newarray;
   save Temparray Temparray;
   clear Temparray;
	Filters.LowCuttoff=Filters.LowCuttoff/Log.Head.SRate;
	Filters.HighCuttoff=Filters.HighCuttoff/Log.Head.SRate;
switch Filters.name
	case 'b'
		 Filters.name='b ';
		if Filters.Type=='low '
			[B,A]=butter(Filters.Order,Filters.LowCuttoff);
		elseif Filters.Type=='high'
			[B,A]=butter(Filters.Order,Filters.HighCuttoff,Filters.Type);
		elseif Filters.Type=='pass'
			[B,A]=butter(Filters.Order,[Filters.LowCuttoff,Filters.HighCuttoff]);
		elseif Filters.Type=='stop'
			[B,A]=butter(Filters.Order,[Filters.LowCuttoff,Filters.HighCuttoff],Filters.Type);
		end
	
	case 'c1'
		if Filters.Type=='low '
			[B,A]=cheby1(Filters.Order,Filters.PassRipple,Filters.LowCuttoff);
		elseif Filters.Type=='high'
			[B,A]=cheby1(Filters.Order,Filters.PassRipple,Filters.HighCuttoff,Filters.Type);
		elseif Filters.Type=='pass'
			[B,A]=cheby1(Filters.Order,Filters.PassRipple,[Filters.LowCuttoff,Filters.HighCuttoff]);
		elseif Filters.Type=='stop'
			[B,A]=cheby1(Filters.Order,Filters.PassRipple,[Filters.LowCuttoff,Filters.HighCuttoff],Filters.Type);
		end
	
	case 'c2'
		if Filters.Type=='low '
			[B,A]=cheby2(Filters.Order,Filters.PassRipple,Filters.LowCuttoff);
		elseif Filters.Type=='high'
			[B,A]=cheby2(Filters.Order,Filters.PassRipple,Filters.HighCuttoff,Filters.Type);
		elseif Filters.Type=='pass'
			[B,A]=cheby2(Filters.Order,Filters.PassRipple,[Filters.LowCuttoff,Filters.HighCuttoff]);
		elseif Filters.Type=='stop'
			[B,A]=cheby2(Filters.Order,Filters.PassRipple,[Filters.LowCuttoff,Filters.HighCuttoff],Filters.Type);
		end
	
	case 'e'
		Filters.name='e ';
		if Filters.Type=='low '
			[B,A]=ellip(Filters.Order,Filters.PassRipple,Filters.StopRipple,'low');
		elseif Filters.Type=='high'
			[B,A]=ellip(Filters.Order,Filters.PassRipple,Filters.StopRipple,Filters.HighCuttoff,Filters.Type);
		elseif Filters.Type=='pass'
			[B,A]=ellip(Filters.Order,Filters.PassRipple,Filters.StopRipple,[Filters.LowCuttoff,Filters.HighCuttoff]);
		elseif Filters.Type=='stop'
			[B,A]=ellip(Filters.Order,Filters.PassRipple,Filters.StopRipple,[Filters.LowCuttoff,Filters.HighCuttoff],Filters.Type);
		end		
	end

Filters.LowCuttoff=Filters.LowCuttoff*Log.Head.SRate;
Filters.HighCuttoff=Filters.HighCuttoff*Log.Head.SRate;
Sign=Movs.newarray;
set(Movs.Button.FS,'value',0)

if get(Movs.Button.Global,'value')==1
	Movs.newarray=filter(B,A,Sign);
	Mov_Movielog('Add',['Filt ',Filters.name,' ',num2str(Filters.Type),' ',num2str(Filters.Order),' ',num2str(Filters.LowCuttoff),' ',num2str(Filters.HighCuttoff),' ',num2str(Filters.PassRipple),' ',num2str(Filters.StopRipple)]) ;
elseif get(Movs.Button.Local,'value')==1
	Movs.newarray(:,Movs.Current_ch)=filter(B,A,Sign(:,Movs.Current_ch));
	Mov_Movielog('Add Local',['Filt ',Filters.name,' ',num2str(Filters.Type),' ',num2str(Filters.Order),' ',num2str(Filters.LowCuttoff),' ',num2str(Filters.HighCuttoff),' ',num2str(Filters.PassRipple),' ',num2str(Filters.StopRipple),' ',num2str(Movs.Badpic)]);
end

    if Movs.Signal.True==1;
       Mov_Movie 'Signal'
    end
	  
end



