function Zeng_Data_Info(varargin)
%Stripchart=get(gcf,'userdata')
%get(gcbf,'tag')%not always
%get(gcf,'tag') %Alway stripchart
global Log
if strcmp('Stripchart',get(gcbf,'tag'));
   FromStripchart=1;
	Stripchart=get(gcf,'userdata');
else
   FromStripchart=0;
   Stripchart=get(gcf,'userdata');
end

Continue=1;
if  ~isempty(Stripchart.Data_Info)
   figure(Stripchart.Data_Info.Figure);
   if  FromStripchart
 		Continue=0;
   else
		close;       
   end
else
end

if Continue
   Data_Info=[];
   Data_Info.Parent=Stripchart.Figure;
   if FromStripchart;
		Data_Info.Figure=figure(...
  			'Units','pixels',...
  			'Position',Log.UD.Ref.Position(Log.UD.HD.Data_Info.Figure,:));
   else
      Data_Info.Figure=dialog(...
  			'Units','pixels',...
        	'Position',Log.UD.Ref.Position(Log.UD.HD.Data_Info.Figure,:));
  	end
   set(Data_Info.Figure,...
     	'Color',[0.8 0.8 0.8], ...
		'MenuBar','none', ...
  		'Name','Data Information',...
	  	'NumberTitle','off',...
  		'Position',Log.UD.Ref.Position(Log.UD.HD.Data_Info.Figure,:), ...
	   'Tag','Data Information',...
      'DeleteFcn',[.... 
      	'Data_Info=get(gcbf,''userdata'');',...
         'Stripchart=get(Data_Info.Parent,''userdata'');',...
         'Stripchart.Data_Info=[];',...
         'set(Stripchart.Figure,''userdata'',Stripchart);',...
         'close(gcbf);']);

   Stripchart.Data_Info.Figure=Data_Info.Figure;
   set(Stripchart.Figure,'userdata',Stripchart);  
	uicontrol('Parent',Data_Info.Figure, ...
		'Units','normalized', ...
		'BackgroundColor',[0.8 0.8 0.8], ...
		'HorizontalAlignment','right', ...
		'Position',[0.01 0.691318 0.12 0.08], ...
		'String','Subject:', ...
		'Style','text', ...
		'Tag','StaticText1');
	uicontrol('Parent',Data_Info.Figure, ...
		'Units','normalized', ...
		'BackgroundColor',[0.8 0.8 0.8], ...
		'HorizontalAlignment','right', ...
		'Position',[0.01 0.565916 0.12 0.08], ...
		'String','Channels:', ...
		'Style','text', ...
		'Tag','StaticText1');
	uicontrol('Parent',Data_Info.Figure, ...
		'Units','normalized', ...
		'BackgroundColor',[0.8 0.8 0.8], ...
		'HorizontalAlignment','right', ...
		'Position',[0.01 0.832797 0.12 0.08], ...
		'String','File Name:', ...
		'Style','text', ...
		'Tag','StaticText1');
	uicontrol('Parent',Data_Info.Figure, ...
		'Units','normalized', ...
		'BackgroundColor',[0.8 0.8 0.8], ...
		'HorizontalAlignment','right', ...
		'Position',[0.01 0.437299 0.12 0.08], ...
		'String','SRate:', ...
		'Style','text', ...
		'Tag','StaticText1');
	uicontrol('Parent',Data_Info.Figure, ...
		'Units','normalized', ...
		'BackgroundColor',[0.8 0.8 0.8], ...
		'HorizontalAlignment','right', ...
		'Position',[0.01 0.302251 0.12 0.08], ...
		'String','Samples:', ...
		'Style','text', ...
		'Tag','StaticText1');
	uicontrol('Parent',Data_Info.Figure, ...
		'Units','normalized', ...
		'BackgroundColor',[0.8 0.8 0.8], ...
		'HorizontalAlignment','right', ...
		'Position',[0.30 0.694534 0.12 0.08], ...
		'String','Date:', ...
		'Style','text', ...
		'Tag','StaticText2');
	uicontrol('Parent',Data_Info.Figure, ...
		'Units','normalized', ...
		'BackgroundColor',[0.8 0.8 0.8], ...
		'HorizontalAlignment','right', ...
		'Position',[0.30 0.569132 0.12 0.08], ...
		'String','Gain:', ...
		'Style','text', ...
		'Tag','StaticText1');
	uicontrol('Parent',Data_Info.Figure, ...
		'Units','normalized', ...
		'BackgroundColor',[0.8 0.8 0.8], ...
		'HorizontalAlignment','right', ...
		'Position',[0.30 0.437299 0.12 0.08], ...
		'String','LUT:', ...
		'Style','text', ...
		'Tag','StaticText1');
	uicontrol('Parent',Data_Info.Figure, ...
		'Units','normalized', ...
		'BackgroundColor',[0.8 0.8 0.8], ...
		'HorizontalAlignment','right', ...
		'Position',[0.30 0.308682 0.12 0.08], ...
		'String','Sys Ver:', ...
		'Style','text', ...
   	'Tag','StaticText1');
	uicontrol('Parent',Data_Info.Figure, ...
		'Units','normalized', ...
		'BackgroundColor',[0.8 0.8 0.8], ...
		'HorizontalAlignment','right', ...
		'Position',[0.01 0.176849 0.12 0.08], ...
		'String','Comment:', ...
		'Style','text', ...
      'Tag','Text.Comment');
   
   

	if nargin == 1     % Normal Data information window
   	Type='text';
	elseif nargin == 2 %   ""    add No head file windows.
   	Type='edit';
    end
   Data_Info.Text.FileName=uicontrol('Parent',Data_Info.Figure, ...
		'Units','normalized', ...
		'BackgroundColor',[1 1 1], ...
		'HorizontalAlignment','left', ...
		'Position',[0.15 0.832797 0.15 0.08], ...
		'Style','text', ...
   	'Tag','Text.FileName');

	Data_Info.Text.Subject = uicontrol('Parent',Data_Info.Figure, ...
		'Units','normalized', ...
		'BackgroundColor',[1 1 1], ...
		'HorizontalAlignment','left', ...
		'Position',[0.15 0.691318 0.15 0.08], ...
		'Style',Type, ...
		'Tag','Text.Subject');
	Data_Info.Text.Channels = uicontrol('Parent',Data_Info.Figure, ...
		'Units','normalized', ...
		'BackgroundColor',[1 1 1], ...
		'HorizontalAlignment','left', ...
		'Position',[0.15 0.565916 0.15 0.08], ...
		'Style',Type, ...
		'Tag','Text.Channels');
	Data_Info.Text.SRate = uicontrol('Parent',Data_Info.Figure, ...
		'Units','normalized', ...
		'BackgroundColor',[1 1 1], ...
		'HorizontalAlignment','left', ...
		'Position',[0.15 0.437299 0.15 0.08], ...
		'Style',Type, ...
		'Tag','Text.SRate');
	Data_Info.Text.Samples = uicontrol('Parent',Data_Info.Figure, ...
		'Units','normalized', ...
		'BackgroundColor',[1 1 1], ...
		'HorizontalAlignment','left', ...
		'Position',[0.15 0.302251 0.15 0.08], ...
		'Style',Type, ...
		'Tag','Text.Samples');
	Data_Info.Text.Date = uicontrol('Parent',Data_Info.Figure, ...
		'Units','normalized', ...
		'BackgroundColor',[1 1 1], ...
		'HorizontalAlignment','left', ...
		'Position',[0.45 0.694534 0.15 0.08], ...
		'Style',Type, ...
		'Tag','Text.Date');
	Data_Info.Text.Gain = uicontrol('Parent',Data_Info.Figure, ...
		'Units','normalized', ...
		'BackgroundColor',[1 1 1], ...
		'HorizontalAlignment','left', ...
		'Position',[0.45 0.569132 0.15 0.08], ...
		'Style',Type, ...
		'Tag','Text.Gain');
	Data_Info.Text.LUT = uicontrol('Parent',Data_Info.Figure, ...
		'Units','normalized', ...
		'BackgroundColor',[1 1 1], ...
		'HorizontalAlignment','left', ...
		'Position',[0.45 0.437299 0.422 0.08], ...
		'Style',Type, ...
		'Tag','Text.LUT');
	Data_Info.Text.Sys_Ver = uicontrol('Parent',Data_Info.Figure, ...
		'Units','normalized', ...
		'BackgroundColor',[1 1 1], ...
		'HorizontalAlignment','left', ...
		'Position',[0.45 0.308682 0.422 0.08], ...
		'Style',Type, ...
		'Tag','Text.Sys_Ver');

	Data_Info.Text.Comment=uicontrol('Parent',Data_Info.Figure, ...
		'Units','normalized', ...
		'BackgroundColor',[1 1 1], ...
		'HorizontalAlignment','left', ...
		'Position',[0.15 0.173633 0.72209 0.08], ...
		'Style',Type, ...
		'Tag','Text.Comment');

	% TEST
    
    % Ok button does not work if you delete the following line
    if FromStripchart
        writeDataInfoFields(Data_Info.Text, Stripchart.Head)
        
    else % from create head file
       writeDataInfoFields(Data_Info.Text, Log.UD.Temp.Head)
    end
    
	if nargin == 1     % Normal Data information window
   	uicontrol('Parent',Data_Info.Figure, ...
	      'Units','normalized', ...
	      'Position',[0.42266 0.0192926 0.163895 0.0836013], ...
	      'String','OK', ...
	      'Tag','OK',...
         'callback',[...
            'Data_Info=get(gcbf,''userdata'');',...
            'Stripchart=get(Data_Info.Parent,''userdata'');',...
            'Stripchart.Data_Info=[];',...
            'set(Stripchart.Figure,''userdata'',Stripchart);',...
            'close(gcbf);']);
		   %'UD=get(0,''userdata'');',...
			%'Comment=get(Data_Info.Text.Comment,''String'');',...
			%'if strcmp(Comment,UD.Head.Comment);',...
			%'figure(10);',...
			%'   Zeng_Share(''Error'',''Are you sure to change the comment ???'');',...
			%'else;',...
			%' figure(20);',...
			%'   close(Data_Info.Figure);',...
      	%'end']);
	elseif nargin == 2 %   ""    add No head file windows.
		uicontrol('Parent',Data_Info.Figure, ...
			'Units','normalized', ...
			'FontUnits','normalized', ...
			'BackgroundColor',[0.8 0.8 0.8], ...
			'FontSize',0.213333, ...
			'HorizontalAlignment','left', ...
			'Position',[0.647482 0.748428 0.206235 0.13522], ...
			'String','These data came from', ...
			'Style','text', ...
			'Tag','StaticText1');
		uicontrol('Parent',Data_Info.Figure, ...
			'Units','normalized', ...
			'FontUnits','normalized', ...
			'BackgroundColor',[0.8 0.8 0.8], ...
			'FontSize',0.102564, ...
			'HorizontalAlignment','left', ...
			'Position',[0.640288 0.569182 0.227818 0.333333], ...
			'Style','frame', ...
			'Tag','Frame1');
	
		Data_Info.OP.PC = uicontrol('Parent',Data_Info.Figure, ...
	      'Units','normalized', ...
	      'BackgroundColor',[0.8 0.8 0.8], ...
	      'Position',[0.676259 0.688679 0.136691 0.081761], ...
	      'String','PC', ...
	      'Style','radiobutton', ...
         'callback',[...
            'Data_Info=get(gcbf,''userdata'');',...
	         'set(Data_Info.OP.PC,''value'',1);',...
            'set(Data_Info.OP.MU,''value'',0);']);
	   Data_Info.OP.MU = uicontrol('Parent',Data_Info.Figure, ...
	      'Units','normalized', ...
	      'BackgroundColor',[0.8 0.8 0.8], ...
	     	'Position',[0.673861 0.578616 0.184652 0.072327], ...
	      'String','Mac or Unix', ...
	      'Style','radiobutton', ...
	      'callback',[...
            'Data_Info=get(gcbf,''userdata'');',...
	         'set(Data_Info.OP.PC,''value'',0);',...
	         'set(Data_Info.OP.MU,''value'',1);']);
	   if strcmp(Log.UD.Temp.Head.Sys_Ver,'CWRU optical system')
	      set(Data_Info.OP.MU,'value',1);
	   else
	      set(Data_Info.OP.PC,'value',1);
	   end
	   uicontrol('Parent',Data_Info.Figure, ...
	      'Units','normalized', ...
	      'Position',[0.28266 0.0192926 0.163895 0.0836013], ...
	      'String','OK', ...
	      'Tag','OK',...
	      'callback',[...
            'Data_Info=get(gcbf,''userdata'');',...
	         'Log.UD.Temp.Head.Subject=get(Data_Info.Text.Subject,''String'');',...
	         'Log.UD.Temp.Head.Chans  =str2num(get(Data_Info.Text.Channels,''String''));',...
	         'Log.UD.Temp.Head.Gain   =str2num(get(Data_Info.Text.Gain,''String''));',...
	         'Log.UD.Temp.Head.LUT    =get(Data_Info.Text.LUT,''String'');',...	         %'UD.Temp.Head.FileName    =get(Data_Info.Text.FileName,''String'');',...	         'UD.Temp.Head.Path   = UD.Temp.Path;',...
	         'Log.UD.Temp.Head.Samples=str2num(get(Data_Info.Text.Samples,''String''));',...
	         'Log.UD.Temp.Head.Date   =get(Data_Info.Text.Date,''String'');',...
	         'Log.UD.Temp.Head.SRate  =str2num(get(Data_Info.Text.SRate,''String''));',...
	         'Log.UD.Temp.Head.Sys_Ver=get(Data_Info.Text.Sys_Ver,''String'');',...
            'Log.UD.Temp.Head.Comment=get(Data_Info.Text.Comment,''String'');',... 
	         'if ~isempty(Log.UD.Temp.Head.Samples) & ~isempty(Log.UD.Temp.Head.Chans);',...%'if length(UD.Temp.Head.Samples)|length(UD.Temp.Head.Chans);',...
	         '   if length(Log.UD.Temp.Data) ~=Log.UD.Temp.Head.Samples*Log.UD.Temp.Head.Chans;',...
	         '        Zeng_Share(''Error'',''Samples and Channels do not match with raw data size'');',...
	         '   else;',...
	         '     Zeng_Share(''Stripchart'',''Initial'');',...
            '     Stripchart=get(gcf,''userdata'');',... 
            '     Stripchart.Data=Log.UD.Temp.Data;',...
            '     Stripchart.Head=Log.UD.Temp.Head;',...
	         'disp(Stripchart.Head);',...
            '     if get(Data_Info.OP.PC,''value'') ==1;',...
	         '        Stripchart.Data=reshape(Stripchart.Data,Stripchart.Head.Samples,Stripchart.Head.Chans);',...
	         '     else;',...
	         '        Stripchart.Data=reshape(Stripchart.Data,Stripchart.Head.Chans,Stripchart.Head.Samples)'';',...
	         '     end;',...
	         '     Stripchart.Current_ch=1;',...
	         '     Stripchart.Time1=1;',...
            '     Stripchart.Time2=Stripchart.Head.Samples;',...
	         '     set(Stripchart.Edit.Channel,''string'',Stripchart.Current_ch);',...
	         '     set(Stripchart.Edit.Time1,''string'',Stripchart.Time1);',...
	         '     set(Stripchart.Edit.Time2,''string'',Stripchart.Time2);',...
	         '     axes(Stripchart.Axes);plot(Stripchart.Data(:,Stripchart.Current_ch));',...
	         '     set(Stripchart.Figure,''name'',[''File name: '' Stripchart.Head.FileName]);',...
	         '     set(Stripchart.Figure,''userdata'',Stripchart);',...
	         '     dlmwrite([Stripchart.Head.Path Stripchart.Head.FileName ''.h''],'''');',...
	         '     FID=fopen([Stripchart.Head.Path Stripchart.Head.FileName ''.h''],''w'');',...
   	      '     fprintf(FID,''=================================\n'');',...
	         '     fprintf(FID,''CWRU Cardio Mapping System header\n'');',...
   	      '     fprintf(FID,''=================================\n'');',...
	         '     fprintf(FID,[''subject\t'' Stripchart.Head.Subject ''\n'']);',...
	         '     fprintf(FID,[''date\t'' Stripchart.Head.Date ''\n'']);',...
	         '     fprintf(FID,[''gain\t'' num2str(Stripchart.Head.Gain) ''\n'']);',...
	         '     fprintf(FID,[''srate\t'' num2str(Stripchart.Head.SRate) ''\n'']);',...
	         '     fprintf(FID,[''samples\t'' num2str(Stripchart.Head.Samples) ''\n'']);',...
	         '     fprintf(FID,[''chans\t'' num2str(Stripchart.Head.Chans) ''\n'']);',...
	         '     fprintf(FID,[''comment\t'' Stripchart.Head.Comment ''\n'']);',...
	         '     fprintf(FID,[''lut\t'' Stripchart.Head.LUT ''\n'']);',...
	         '     fprintf(FID,[''SysVer\t'' Stripchart.Head.Sys_Ver ''\n'']);',...
	         '     Status=fclose(FID);',...
	         '     Log.UD.Temp.Head=[];',...
	         '     Log.UD.Temp.Data=[];',...
	         '     if Status== -1;',... % The head file was not able to save.
	         '         Zeng_Share(''Error'',''I Could not save head file for you'');',...
            '     end;',...
            '     close(Data_Info.Figure);',...
	         '   end;',...% if length(UD.Data) ~=UD.Head.Samples*UD.Head.Chans;',...
	         'else;',...
	         '   Zeng_Share(''Error'',''Samples and Channels do not match with raw data size'');',... %'   Zeng_Share(''Error'',''Do not be Stupid to add letters in "Samples and Channels" parts'');',...
	         'end;']); %   'if length(UD.Head.Samples)|length(UD.Head.Chans);',...
	



		   uicontrol('Parent',Data_Info.Figure, ...
		      'Units','normalized', ...
	      	'Position',[0.56057 0.0257235 0.16152 0.0803859], ...
		      'String','Cancel', ...
	   	   'Tag','Cancel',...
	      	'callback',[...
	            'Data_Info=get(gcbf,''userdata'');',...
   	         'Stripchart=get(Data_Info.Parent,''userdata'');',...
      	      'Stripchart.Data_Info=[];',...
         	   'set(Stripchart.Figure,''userdata'',Stripchart);',...
	            'Log.UD.Temp.Head=[];',...%'set(Stripchart.Text.FileName,''string'','' '');',...
		         'close(gcbf);']);
	end %	if nargin == 1     % Normal Data information window
	set(Data_Info.Figure,'userdata',Data_Info);
end %if  ~isempty(Stripchart.Data_Info.Figure)
end

% Writes Stripchart.Head values into Data_Info.Text struct. 
% 
% Uses try-catch to handle errors so that they don't stop the rest of the 
% fields from being assigned.
% 
% @param data_info(struct): where the UI gets the info to display
% @param stripchart(struct): info fields from the head
function writeDataInfoFields(data_info, head)
    
    % specify the necessary fields to populate in the Data Info Window
    infoFields = [
        "Subject";
        "Channels";
        "Gain";
        "LUT";
        "FileName";
        "Samples";
        "Date";
        "SRate";
        "Sys_Ver";
        "Comment"
        ];
    
    % iterate over all info fields to apply the set() function
    for field = infoFields.'
        try
            if strcmp(field,"Channels") % special case
                set(data_info.(field),'String',head.Chans)
            else
                set(data_info.(field),'String',head.(field))
            end
        catch err
            disp(err)
        end
    end
    
end