function Zeng_Error(Message)
global Log;
E = dialog('name','Error',...
   'Position',[Log.UD.ScreenSize(1)/2-320/2 Log.UD.ScreenSize(2)/2-160/2 320 160],...
   'tag','ZengError');
Temp.FG_Size=get(E,'position');
uicontrol('Parent',E, ...
   'BackgroundColor',get(E,'Color'), ...
   'fontsize',12,...
   'fontweight','bold',...
   'Position',[1 120 320 20], ...         'String','Are you nuts !!!', ...
   'String','ATTENTION', ...
   'Style','text');
uicontrol('Parent',E, ...
   'BackgroundColor',get(E,'Color'), ...
   'HorizontalAlignment','center',...
   'Position',[1 40 Temp.FG_Size(3) 60], ...
   'String',Message, ...
   'Style','text');
uicontrol('Parent',E, ...
   'callback','close',...
   'Units','points', ...
   'Position',[90 15 57.75 24],...
   'string','OK');
